services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
    environment:
      - SPOTIPY_CACHE_PATH=/data/.cache
